### ISSUE TITLE
Duthie bot unresponsive 

### ISSUE THREAD

**Issue by docpeep** [tfrizzell/duthie-bot#1]
I'm not very tech savvy, but i love duthie bot. Unfortunately, he no longer allows users to give commands. 

"-duthie unwatch type=scores league=LGAHL team=CharlotteCheckers channel= #score"

"I'm sorry, @JClaus33, but you aren't allow to do that"

He says this to almost every command and in new servers when the owner of the server tries set him up. 

Please help!

**Comment by tfrizzell** [comment]
I hadn't noticed this issue before. I'm working on a top-to-bottom rewrite of the bot in C#, with better adherence to new features in Discord (such as slash commands). It should work much better once that's done.

**Comment by tfrizzell** [comment]
Closing this issue. Duthie Bot v3.0.0 is in testing now, with plans to go live around mid-January.
