### ISSUE TITLE
Doesnt list/Find NCAA teams

### ISSUE THREAD

**Issue by kaliyevl34l** [tfrizzell/duthie-bot#26]
Tried to get the bot to list/add watcher for NCAA teams and it says it didn't find any teams 

![Screenshot_20240213_203304_Discord](https://github.com/tfrizzell/duthie-bot/assets/151794157/41be0b56-d1ed-4147-bf00-630d09ece0e4)
![Screenshot_20240213_203310_Discord](https://github.com/tfrizzell/duthie-bot/assets/151794157/5b55dcb0-e8e3-4b5e-87fd-2235963e3d80)

**Comment by tfrizzell** [comment]
This has been resolved.
